version: "3"
services:
  mysql:
    restart: unless-stopped
    container_name: autodrive-mysql
    image: mysql:latest
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: autodrive
      MYSQL_USER: autodrive
      MYSQL_PASSWORD: autodrive
      MYSQL_ROOT_PASSWORD: autodrive

  webserver:
    restart: unless-stopped
    container_name: autodrive-webserver
    image: nginx:stable-alpine
    working_dir: /app
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    networks:
      default:

  backend:
    container_name: autodrive-fpm
    build: ./.docker/php/fpm
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./.docker/php/fpm/php-override.ini:/usr/local/etc/php/conf.d/php-override.ini
      - ./.docker/php/composer-cache:/root/.composer/
      - ./:/app

networks:
  default:
